language: julia
os:
   - linux
   - osx
julia:
   - 0.6
   - nightly
after_success:
   - julia -e 'cd(Pkg.dir("ArrayViews")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
notifications:
  email: false
